### ISSUE TITLE
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders

### ISSUE THREAD

**Issue by masteroleary** [mgyongyosi/VuejsSSRSample#2]
Edit - Fixed and created pull request

Original:
1) dotnet restore
2) npm install
3) npm install babel-core
4) webpack --config webpack.server.config.js gives this error  
`
$ webpack --config webpack.server.config.js
Hash: 8a3e7278453b7c4c1782
Version: webpack 3.8.1
Time: 1408ms
           Asset    Size  Chunks                    Chunk Names
bundle.server.js  414 kB       0  [emitted]  [big]  main
  [50] ./VueApp/server.js 394 bytes {0} [built]
  [51] ./VueApp/app.js 866 bytes {0} [built]
  [58] ./VueApp/vuex/store.js 1.18 kB {0} [built]
  [59] ./VueApp/vuex/actions.js 662 bytes {0} [built]
    + 168 hidden modules

ERROR in ./node_modules/axios/lib/adapters/http.js
Module not found: Error: Can't resolve 'json' in 'c:\WORKFOLDER\VuejsSSRSample\VuejsSSRSample'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'json-loader' instead of 'json',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
      @ ./node_modules/axios/lib/adapters/http.js 12:10-41
      @ ./node_modules/axios/lib/defaults.js
      @ ./node_modules/axios/lib/axios.js
      @ ./node_modules/axios/index.js
      @ ./VueApp/vuex/actions.js
      @ ./VueApp/vuex/store.js
      @ ./VueApp/app.js
      @ ./VueApp/server.js

`

**Comment by mgyongyosi** [comment]
Thank you!
